### PR TITLE
await

### PR DESCRIPTION
**Pull request by futurGH**

### CODE REVIEW

**Review by ShreyanJain9 — APPROVED** [review]
javascript is a joke

**Comment by ShreyanJain9** [comment]
oh 
```
[poll-blue] [2024-03-20 02:10:12] error: Uncaught SyntaxError: The requested module 'https://esm.sh/v115/@atproto/api@0.2.3' does not provide an export named 'RichText'
[poll-blue] [2024-03-20 02:10:12] import { AtpAgent, AppBskyFeedPost, AppBskyRichtextFacet, RichText } from "https://esm.sh/v115/@atproto/api@0.2.3"
[poll-blue] [2024-03-20 02:10:12]                                                           ^
[poll-blue] [2024-03-20 02:10:12]     at <anonymous> (file:///app/app/poll-utils.ts:1:59)
```

**Comment by futurGH** [comment]
we're on like 1.2.2 now

**Comment by futurGH** [comment]
nvm 0.12.2

**Comment by ShreyanJain9** [comment]
oh lmao this thing is old

**Pull request merged**
